### ISSUE TITLE
No need to wait after Wire.requestFrom() and it should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [DFRobot/DFRobot_BNO055#1]
In the file "DFRobot_BNO055/DFRobot_BNO055.cpp" there is in four places a while-loop after the Wire.requestFrom() like this: `while (Wire.available() < 6);`
There is no need to wait for something, those lines can be removed.

In the function "readByte()", there is a Wire.endTransmission() after the Wire.requestFrom(), that Wire.endTransmission() just before the return can be removed as well.

**Comment by wxzed** [comment]
@Koepel Thank you for your feedback, your question has been modified
